---
- name: Get VxRail Cluster details"
  hosts: localhost
  gather_facts: no
  vars:
    - grp:  "{{ groups['vxrail'] }}"
    - no_logging: no

  collections:
   - dellemc.vxrail
  roles:
  - vx-clusterinfo
