---
- name: Get the VxRail host health"
  hosts: control
  vars:
    vxrail_hosts: "{{ vxm }}"
    vxrail_auth_user: "{{ vcadmin }}"
    vxrail_auth_password: "{{ vcpasswd }}"
  tasks:
   - name: "get vxrail job requests"
     uri:
       url: "https://{{ vxrail_hosts }}/rest/vxm/v1/requests"
       headers:
        "Content-Type": "application/json"
        "Accept": "application/json"
        "Cache-Control": "no-cache"
       body_format: json
       return_content: yes
       user: "{{ vxrail_auth_user }}"
       password: "{{ vxrail_auth_password }}"
       force_basic_auth: yes
       validate_certs: no
       status_code: 200
     register: requests

   - debug: msg="{{ requests.json[0] | json_query(jmesquery) }}"
     vars:
       jmesquery: "{id: id, task: owner, state: state, complete: progress}"
#       var: item
#     loop: "{{ requests.json[-1] | json_query('[*].{id: id, task: owner, state: state}') }}"
