---
   - name: "get vxrail health status"
     uri:
       url: "https://{{ item }}/rest/vxm/v1/hosts"
       headers:
        "Content-Type": "application/json"
        "Accept": "application/json"
        "Cache-Control": "no-cache"
       body_format: json
       return_content: yes
       user: "{{ vc_admin }}"
       password: "{{ vc_password }}"
       force_basic_auth: yes
       validate_certs: no
       status_code: 200
     register: "name"
     loop: "{{ vxrail_hosts }}"

   - name: "JSON output from VxRail Host query"
     debug:
       msg: "{{ name.results[0].content }}"
