---
- hosts: localhost
  vars_files:
    - /etc/ansible/host_vars/{{ vxm }}
  collections:
  - vmware
  tasks:
  - name: "{{ vcenter }} port group mtu setting"
    vmware_portgroup_info:
      hostname: "{{ vcenter }}"
      username: "{{ vcadmin }}"
      password: "{{ vcpasswd }}"
      cluster_name: "{{ cluster_name }}"
      validate_certs: false
    delegate_to: localhost
    register: vcenter_pginfo

  - debug:
      msg: "{{ vcenter_pginfo }}"

  - name: "{{ esxhost }} port group mtu setting"
    vmware_portgroup_info:
      hostname: "{{ vcenter }}"
      username: "{{ vcadmin }}"
      password: "{{ vcpasswd }}"
      esxi_hostname: "{{ esxhost }}"
      validate_certs: false
    delegate_to: localhost
    register: esx_pginfo

  - debug:
      msg: "{{ esx_pginfo }}"
