---
- hosts: localhost
  gather_facts: yes
  collections:
  - vmware
  tasks:
  - name: Maint Mode test
    vmware_vm_info:
      hostname: "{{ vcenter }}"
      username: "{{ vcadmin }}"
      password: "{{ vcpasswd }}"
      validate_certs: false
    delegate_to: localhost
    register: vm_info

  - set_fact:
      cluster: "{{ item.cluster }}"
    with_items:
      - "{{ vm_info.virtual_machines | json_query(query) }}"
    vars:
      query: "[?guest_name=='VxRail Manager']"

  - debug:
      msg: "{{ cluster }}"

  - name: Get vCenter Facts
    vmware_cluster_info:
      hostname: "{{ vcenter }}"
      username: "{{ vcadmin }}"
      password: "{{ vcpasswd }}"
      cluster_name: "{{ cluster }}"
      validate_certs: false
    delegate_to: localhost
    register: cluster_info

  - debug:
       msg: "{{ cluster_info }}"
