---
- hosts: localhost
  gather_facts: yes
  collections:
  - vmware
  tasks:
  - name: Virtual Machine Info
    vmware_vm_info:
      hostname: "{{ vcenter }}"
      username: "{{ vcadmin }}"
      password: "{{ vcpasswd }}"
      validate_certs: false
    delegate_to: localhost
    register: vm_info

  - set_fact:
      cluster: "{{ item.cluster }}"
    with_items:
      - "{{ vm_info.virtual_machines | json_query(query) }}"
    vars:
      query: "[?guest_name=='VxRail Manager']"

  - debug:
      msg: "{{ cluster }}"

  - name: Get vCenter Facts
    vmware_vsan_health_info:
      hostname: "{{ host }}"
      username: "root"
      password: "{{ vcpasswd }}"
      cluster_name: "{{ cluster }}"
      validate_certs: false
    delegate_to: localhost
    register: vsan_info

  - debug:
       msg: "{{ vsan_info }}"
