---
 -  name: Place node into maintenance mode
    vmware_maintenancemode:
      hostname: "{{ vcenter }}"
      username: "{{ vcadmin }}"
      password: "{{ vcpasswd }}"
      esxi_hostname: "{{ host }}"
      vsan: ensureObjectAccessibility
      evacuate: yes
      timeout: 3600
      validate_certs: false
      state: "present"
    delegate_to: localhost

 - name: Sleep to allow VxM to update
   pause:
     minutes: 3

 -  name: Remove node {{ host }}
    dellemc.vxrail.vx_rmnode:
      ip: "{{ vxm }}"
      vcadmin: "{{ vcadmin }}"
      vcpasswd: "{{ vcpasswd }}"
      esxhost: "{{ host }}"
      root: "{{ root }}"
      root_passwd: "{{ root_passwd }}"
    register: output

 - debug:
     msg: "{{ output }}"
