---
- hosts: localhost
  name: Manage System Power - Graceful shutdown
  gather_facts: False
  tasks:
  - name: Shutdown system power gracefully
    redfish_command:
      category: Systems
      command: PowerGracefulShutdown
      baseuri: "{{ ip }}"
      username: "{{ username }}"
      password: "{{ password }}"
