---
- hosts: localhost
  name: Manage System Power - Force Off
  gather_facts: False
  tasks:
  - name: Turn system power off
    redfish_command:
      category: Systems
      command: PowerForceOff
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
