---
- name: Get the VxRail host health"
  hosts: localhost
  gather_facts: no
  vars_files:
    - /etc/ansible/host_vars/{{ vxm }}
  vars:
    - grp:  "{{ groups['vxrail'] }}"
    - no_logging: no

  collections:
   - dellemc.vxrail
  roles:
  - vx-health
