---
- hosts: localhost
  gather_facts: False
  vars_files:
     - /etc/ansible/host_vars/{{ vxm }}
  tasks:
    - name: 
      dellemc.vxrail.vx_mgt_ephemeral:
        vcenter: "{{ vcenter }}"
        vcadmin: "{{ vcadmin }}"
        vcpasswd: "{{ vcpasswd }}"
        mtu: "{{ mtu }}"
        port: 443
      register: status

    - debug:
        msg:  "{{status}}"
      when: status.failed == false
