---
   - name: "get vxrail health status"
     tags:
      - host1
     uri:
       url: "https://{{ vxrail_hosts }}/rest/vxm/v1/hosts"
       headers:
        "Content-Type": "application/json"
        "Accept": "application/json"
        "Cache-Control": "no-cache"
       body_format: json
       return_content: yes
       user: "{{ vc_admin }}"
       password: "{{ vc_password }}"
       force_basic_auth: yes
       validate_certs: no
       status_code: 200
     register: jsondata

   - name: "JSON output from VxRail Host query"
     set_fact:
        node1: "{{ jsondata.json[0] }}"
   
   - name: Run Report
     become: no
     local_action: template src=node1.j2 dest=/tmp/report.txt
     run_once: True
     changed_when: False
      
