---
# Use the VxRail API to get cluster status
 -  name: "Add Node to Cluster"
    dellemc.vxrail.vx_addnode:
      vcadmin: "{{ vcadmin }}"
      vcpasswd: "{{ vcpasswd }}"
      ip: "{{ vxm }}"
      esxhost: "{{ esxhost }}"
      vxadmin: "{{ vxadmin }}"
      vxpasswd: "{{ vxpasswd }}"
      mgt_ip: "{{ mgt_ip }}"
      mgt_gw: "{{ mgt_gw }}"
      vsan_ip: "{{ vsan_ip }}"
      vmotion_ip: "{{ vmotion_ip }}"
      witness_ip: "{{ witness_ip }}"
      root_passwd: "{{ root_passwd }}"
    register: output

 - debug:
     msg: "{{ output }}"
