---
# Use the VxRail API to get firmware list
 - name: Firmware Report
   include: cluster.yml
   when: group is undefined
       
 - name: Perform Task on all clusters in "{{ grp }}"
   include: group.yml
   when: group is defined
