---
# Initiate VxRail Cluster Deployment via the VxRail Manager API
 - name: Initialize VxRail Cluster
   vx-init:
     ip: "{{vxm}}"
     cfg: "{{config}}"
   register: cluster

 - debug:
     msg: "{{cluster}}"
