---
# Use the VxRail API to Convert vCenter
 -  name: Executing VxRail Module...
    dellemc.vxrail.vx_vcmode:
     ip: "{{ vxm }}"
     vcadmin: "{{ vcadmin }}"
     vcpasswd: "{{ vcpasswd }}"
     mode: "{{ mode }}"
    register: vx_facts

 - name: "Display Results"
   debug:
     msg: "{{ vx_facts }}"
