---
# Initiate VxRail Cluster Deployment via the VxRail Manager API
 - name: Initialize VxRail Cluster
   dellemc.vxrail.vx_init:
     ip: "{{ vxm }}"
     cfg: "{{ config }}"
   register: cluster

 - debug:
     msg: "{{ cluster }}"
